GET http://localhost:3000/users

###
GET http://localhost:3000/users/627ed8e55fb700a6abe068a4

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Samantha",
    "Univ": "University of Dayton",
    "GradDate": "09/09/2022"
}

###

DELETE http://localhost:3000/users/627df504021f6c3f05f3cc9b

###

PATCH   http://localhost:3000/users/627df4f2021f6c3f05f3cc98
Content-Type: application/json

{
     "name": "Jason",
     "Univ": "University of Florida"
}