GET http://localhost:3000/users

###
GET http://localhost:3000/users/627df431021f6c3f05f3cc8e

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Jessie",
    "Univ": "UNC Charlotte",
    "GradDate": "10/08/2022"
}

###

DELETE http://localhost:3000/users/627df4b2021f6c3f05f3cc90

###

PATCH   http://localhost:3000/users/627df4c5021f6c3f05f3cc94
Content-Type: application/json

{
     "name": "Chiru"
}